development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  pool: 10
  database: msgenlabprod
  username: root
  password: sqlubuntu

test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  pool: 10
  database: msgenlabprod
  username: root
  password: sqlubuntu

production:
  adapter: mysql2
  encoding: utf8
  url:  <%= ENV["DATABASE_STATS_URL"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>
